name: Update poster

on:
  schedule:
    - cron: '0 8 0 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.10
          cache: pip
          # todo add cache
          # cache-dependency-path: 

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -U github_poster

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Generate poster
        run: |
          # generate to where?
          github_poster github --github_user_name "${{ github.actor }}" --with-skyline
          github_poster leetcode --leetcode_cookie ${{ secrets.LEETCODE_COOKIE }} --year 2021-2022 --cn

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: '.'
          default_author: github_actions
          message: 'Update poster daily'
        
