name: Update poster

on:
  schedule:
    # Run at 1 am every day
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: |
          pip install -U setuptools pip wheel
          pip install -r requirements.txt
          playwright install firefox

      - name: Font cache
        uses: actions/cache@v2
        id: font-cache
        with:
          path: ./fonts
          key: ${{ runner.os }}-font-cache

      - name: Download fonts
        if: steps.font-cache.outputs.cache-hit != 'true'
        run: for i in simhei.ttf simkai.ttf simsun.ttc simsunb.ttf simfang.ttf; do wget -P fonts/ https://xugr.keybase.pub/static/fonts/$i; done

      - name: Install fonts
        run: |
          mkdir -p ~/.local/share/fonts && cp -r fonts/* ~/.local/share/fonts/
          fc-cache -rv

      - name: Generate poster
        env:
          LC_USERNAME: j178
          LC_PASSWORD: ${{ secrets.LC_PASSWORD }}
          SM_TOKEN: ${{ secrets.SM_TOKEN }}
          GH_USERNAME: j178
          IN_GH_ACTION: true
        run: python gen.py

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: 'README.md'
          default_author: github_actions
          message: 'Update poster daily'
